[book]
title = "STM32G431KB Documentation"
authors = ["Jason Teng"]
language = "en"
multilingual = false
src = "docs_src/src"

[build]
build-dir = "docs"

[output.html]
additional-css = ["docs_src/ferris.css", "docs_src/theme/2018-edition.css"]
additional-js = ["docs_src/ferris.js"]
git-repository-url = "https://github.com/jasonyang-ee/STM32G431KB"
